[package]
name = "radar-runner"
version = "0.3.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10"
clap = { version = "4", features = ["derive"] }
toml = "0.9"
dirs = "6.0.0"
